//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public Animal()
        {
            this.MovimientosAnimal = new HashSet<MovimientosAnimal>();
        }
    
        public int Id { get; set; }
        public string IdentificacionAnimal { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> CategoriaEspecieId { get; set; }
        public Nullable<int> EstablecimientoId { get; set; }
        public string MedidaEdad { get; set; }
        public Nullable<int> EstadoAnimalId { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> LoteId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual EstadoAnimal EstadoAnimal { get; set; }
        public virtual Lote Lote { get; set; }
        public virtual ICollection<MovimientosAnimal> MovimientosAnimal { get; set; }
    }
}
