//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraLecturasAcciones
    {
        public int Id { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Token { get; set; }
        public string IdentificacionEquipo { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
        public string ModeloEquipo { get; set; }
        public Nullable<int> PinAnalogo { get; set; }
        public string Valor { get; set; }
        public Nullable<int> PinDigital { get; set; }
        public string AccionEjecutada { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<long> FechaRegistroUnix { get; set; }
        public string TareaEjecutada { get; set; }
    }
}
