//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodegaEstablecimiento
    {
        public int Id { get; set; }
        public Nullable<int> EstablecimientoId { get; set; }
        public Nullable<int> AlimentoId { get; set; }
        public string NumeroSerie { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> CantidadStock { get; set; }
        public Nullable<int> MedicamentoId { get; set; }
        public Nullable<bool> Vigente { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
