//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especie
    {
        public Especie()
        {
            this.CategoriaEspecie = new HashSet<CategoriaEspecie>();
            this.EmpresaEspecie = new HashSet<EmpresaEspecie>();
            this.MovimientosAnimal = new HashSet<MovimientosAnimal>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Vigente { get; set; }
    
        public virtual ICollection<CategoriaEspecie> CategoriaEspecie { get; set; }
        public virtual ICollection<EmpresaEspecie> EmpresaEspecie { get; set; }
        public virtual ICollection<MovimientosAnimal> MovimientosAnimal { get; set; }
    }
}
