//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establecimiento
    {
        public Establecimiento()
        {
            this.Animal = new HashSet<Animal>();
            this.MovimientosAnimal = new HashSet<MovimientosAnimal>();
            this.UsuarioEstablecimiento = new HashSet<UsuarioEstablecimiento>();
        }
    
        public int Id { get; set; }
        public string RUP { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Animal> Animal { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<MovimientosAnimal> MovimientosAnimal { get; set; }
        public virtual ICollection<UsuarioEstablecimiento> UsuarioEstablecimiento { get; set; }
    }
}
