//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeloComponentes
    {
        public int Id { get; set; }
        public Nullable<int> ComponenteId { get; set; }
        public Nullable<int> ModeloId { get; set; }
        public Nullable<int> PinAnalogo { get; set; }
        public Nullable<int> PinDigital { get; set; }
        public string Descripcion { get; set; }
        public string PinDigitalDiametro { get; set; }
        public string PinDigitalLitroXMinuto { get; set; }
    
        public virtual Componente Componente { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
