//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosAnimal
    {
        public int Id { get; set; }
        public Nullable<int> TipoMovimientoId { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public string KGIngreso { get; set; }
        public string KGSalida { get; set; }
        public string KGGanados { get; set; }
        public string PrecioCompra { get; set; }
        public string PrecioVenta { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<int> DiasEngorda { get; set; }
        public string PromedioKGDia { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public Nullable<int> AlimentoId { get; set; }
        public Nullable<int> MedicamentoId { get; set; }
        public string AlimentoInvertidoKG { get; set; }
        public Nullable<System.DateTime> FechaAplicacionAlimento { get; set; }
        public Nullable<System.DateTime> FechaAplicacionMedicamento { get; set; }
        public Nullable<int> DosisMedicamentAplicada { get; set; }
        public string Observacion { get; set; }
        public string RutMv { get; set; }
        public string NombreMv { get; set; }
        public Nullable<int> EstablecimientoId { get; set; }
        public Nullable<int> EspecieId { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
    }
}
