//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.RolRecurso = new HashSet<RolRecurso>();
            this.UsuarioRecurso = new HashSet<UsuarioRecurso>();
        }
    
        public int Id { get; set; }
        public string Modulo { get; set; }
        public string Url { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public Nullable<int> SistemaId { get; set; }
        public string Color { get; set; }
        public string ColorLetra { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Sistema Sistema { get; set; }
        public virtual ICollection<RolRecurso> RolRecurso { get; set; }
        public virtual ICollection<UsuarioRecurso> UsuarioRecurso { get; set; }
    }
}
