//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sistema
    {
        public Sistema()
        {
            this.Recurso = new HashSet<Recurso>();
            this.UsuarioSistema = new HashSet<UsuarioSistema>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Color { get; set; }
        public string ColorLetra { get; set; }
    
        public virtual ICollection<Recurso> Recurso { get; set; }
        public virtual ICollection<UsuarioSistema> UsuarioSistema { get; set; }
    }
}
