//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenPlaca
    {
        public TokenPlaca()
        {
            this.ConfiguracionPlaca = new HashSet<ConfiguracionPlaca>();
        }
    
        public int Id { get; set; }
        public string Token { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> ModeloId { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> ValorSensor { get; set; }
        public Nullable<int> PorcentajeCorrespondiente { get; set; }
        public Nullable<int> ValorBajo { get; set; }
    
        public virtual ICollection<ConfiguracionPlaca> ConfiguracionPlaca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
