//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.TokenPlaca = new HashSet<TokenPlaca>();
            this.UsuarioEstablecimiento = new HashSet<UsuarioEstablecimiento>();
            this.UsuarioRecurso = new HashSet<UsuarioRecurso>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
            this.UsuarioSistema = new HashSet<UsuarioSistema>();
            this.PanelControl = new HashSet<PanelControl>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NombrePersona { get; set; }
        public string ApellidosPersona { get; set; }
        public string RutPersona { get; set; }
        public string EmailPersona { get; set; }
        public Nullable<bool> Vigente { get; set; }
    
        public virtual ICollection<TokenPlaca> TokenPlaca { get; set; }
        public virtual ICollection<UsuarioEstablecimiento> UsuarioEstablecimiento { get; set; }
        public virtual ICollection<UsuarioRecurso> UsuarioRecurso { get; set; }
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
        public virtual ICollection<UsuarioSistema> UsuarioSistema { get; set; }
        public virtual ICollection<PanelControl> PanelControl { get; set; }
    }
}
