//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSoft.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioEstablecimiento
    {
        public int Id { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> EstablecimientoId { get; set; }
        public Nullable<int> SistemaId { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
